### ISSUE TITLE
Is there a fix to show the line continuation icon when the mode is enabled?

### ISSUE THREAD

**Issue by Dima-369** [protesilaos/spacious-padding#1]
See here:

![image](https://github.com/protesilaos/spacious-padding/assets/15002298/99bf7c8b-72f5-430f-a9d8-96613aa2eb93)

But with the mode enabled, those are missing?

![image](https://github.com/protesilaos/spacious-padding/assets/15002298/a1871987-ed81-4808-a8cd-7f84a11d01d2)

**Comment by protesilaos** [comment]
Thank you @Dima-369!  I just made a change that fixed it on my end.

**Comment by Dima-369** [comment]
I tried it out and it also works for me. Thanks for the prompt fix :)

I definitely like the feel this gives!

**Comment by protesilaos** [comment]
Very well!  We can safely close this now.  Thank you!
