### ISSUE TITLE
Possible bug in `spacious-padding-set-window-divider`

### ISSUE THREAD

**Issue by larsen** [protesilaos/spacious-padding#11]
Hello Protesilaos, 

first of all thank you for this package, I really like the aesthetic changes it allows.

While working on my configuration I found a condition that perhaps should be addressed (in the code or the documentation).

Reading the docstring for `spacious-padding-widths` I thought that it was not required to specify all the elements in the new plist.  For example, at a certain point it says (emphasys added by me):

> The more specific keys `:left-fringe-width` and  `:right-fringe-wdith` **can** be used for finer control.

I extended this and interpreted the instructions as they were saying that all keys are optional, and somehow defaults are enforced for those not specified.

But, elsewhere in the code:

https://github.com/protesilaos/spacious-padding/blob/21be66a8293292234a7e4624c35f6645a044f7fa/spacious-padding.el#L261

Since I initially didn't specify a value for `:right-divider-width`, the call to `plist-get` returns `NIL`, which `>` does not like.

I think there should be a guard, a default value, or a note in the docstring specifying what values are mandatory.

**Comment by protesilaos** [comment]
Hello @larsen!

Yes, this is a good point. I think it is better to have reasonable fallback values for everything and to assume that the user opts in to them.

**Comment by protesilaos** [comment]
I believe this issue is done, but I forgot to close it. Doing it now. Thank you!
