### ISSUE TITLE
fringe background does not respect buffer-face-mode

### ISSUE THREAD

**Issue by zhenhua-wang** [protesilaos/spacious-padding#12]
Hi, thank you for this wonderful package. I find the following bug: `fringe` is always the same color as the default background. It does not consider the background of `buffer-face-mode-face`. Any idea to fix this?

**Comment by protesilaos** [comment]
> From: Zhenhua Wang ***@***.***>
> Date: Sat, 13 Apr 2024 12:17:40 -0700
>
> Hi, thank you for this wonderful package.

You are welcome!

> I find the following bug: `fringe` is always the same color as the
> default background. It does not consider the background of
> `buffer-face-mode-face`. Any idea to fix this?

Can you show me an example? The uses I have seen of that is in
variable-pitch-mode, where it gets the variable-pitch face. That should
normally not have any background.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by zhenhua-wang** [comment]
Thanks for checking! You're right. It works fine, is it my theme's issue.
