### ISSUE TITLE
Unexpected behaviour regarding mode lines border and background colors

### ISSUE THREAD

**Issue by renbus** [protesilaos/spacious-padding#16]
Hello,

I would like to know if the following is intended, I believe it is not.

First, I start with `emacs -Q`.

Then, if I evaluate `(describe-face 'mode-line)`, the following is set by default, that's Emacs default mode-line:

Foreground: black
Background: grey75
Box: (:line-width -1 :style released-button)

(Everything else is unspecified.)

Then I evaluate the following:

```
(package-initialize)
(spacious-padding-mode 1)
```

The padding kicks in, like I would expect, but the mode-lines background color turns white, with a grey thick border. If I re-evaluate `(describe-face 'mode-line)`, I now get the following:

Foreground: unspecified
Background: unspecified
Box: (:line-width 6 :color grey75 :style nil)

Why did `spacious-padding-mode` changed the appearance of the mode-line like this (more precisely, why did it change the Foreground and Background colors)? The manual, at 1.2, says:

> By default, ‘spacious-padding-mode’ does not refashion the mode lines
> other than adding to them some extra padding (see Set the exact
> spacing values).

That's what I would have expected, so shouldn't the mode-line have remained with a "grey75" background...?

If then I evaluate `(spacious-padding-mode -1)`, and `(describe-face 'mode-line)`, everything is now "unspecified", and the background of mode-lines remain white.

Strangely, if I re-evaluate `(spacious-padding-mode 1)` again, now the mode-lines get a black border...! And the `(describe-face 'mode-line)` now says that "Foreground" and "Background" are still unspecified, while "Box" is now "(:line-width 6 :color white :style nil)" (while it appears black!).

In other words, how come is Spacious Padding changing the mode lines foreground and background colors? Shouldn't it simply modify the padding (thus the mode-lines borders)?

I am using:

GNU Emacs 29.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.41,
cairo version 1.18.0) on Arch Linux

Configured using:
 'configure --with-pgtk --with-native-compilation=aot
 --sysconfdir=/etc --prefix=/usr --libexecdir=/usr/lib
 --with-tree-sitter --localstatedir=/var --with-cairo
 --disable-build-details --with-harfbuzz --with-libsystemd
 --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe
 -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat
 -Werror=format-security -fstack-clash-protection -fcf-protection -g
 -ffile-prefix-map=/build/emacs/src=/usr/src/debug/emacs -flto=auto'
 'LDFLAGS=-Wl,-O1 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro
 -Wl,-z,now -Wl,-z,pack-relative-relocs -flto=auto'
 'CXXFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt
 -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security
 -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -g
 -ffile-prefix-map=/build/emacs/src=/usr/src/debug/emacs -flto=auto''

Thanks a lot for your support and great packages!

**Comment by ksafford** [comment]
I also experience this when using, say, ef-themes and spacious-padding mode.

The modeline color is set by the theme but then removed once spacious-padding mode is enabled. 

I'd be happy to try to take this issue if I could get some guidance as to where to start looking into it.

**Comment by protesilaos** [comment]
> From: Kevin Safford ***@***.***>
> Date: Mon, 19 Aug 2024 11:02:55 -0700
>
> I also experience this when using, say, ef-themes and spacious-padding
> mode.

I can reproduce the original issue with 'emacs -Q'. Will check it out now.

> The modeline color is set by the theme but then removed once
> spacious-padding mode is enabled.
>
> I'd be happy to try to take this issue if I could get some guidance as
> to where to start looking into it.

I cannot reproduce this with the ef-themes though (neither with the
modus-themes or standard-themes).

Let me see what is happening and update the package accordingly.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by protesilaos** [comment]
I think we have a bug in Emacs here. I am trying all the following with an instance of Emacs that I launch with `emacs -Q`.

If I do not load any theme, then the following code snippets evaluated one-by-one will show that the background of the `mode-line` is erased:

```elisp
(face-attribute 'mode-line :background)
;; => "grey75"

(custom-set-faces
 '(mode-line ((t :box (:color "red")))))
;; The above changes the mode line border to red.

(face-attribute 'mode-line :background)
;; => unspecified
```

Whereas if I load a theme, then the `custom-set-faces` does not override the background of the face it modifies:

```elisp
(load-theme 'modus-operandi)

(face-attribute 'mode-line :background)
;; => "#c8c8c8"

(custom-set-faces
 '(mode-line ((t :box (:color "red")))))
;; The above changes the mode line border to red.

(face-attribute 'mode-line :background)
;; => "#c8c8c8"
```

Maybe this is why I never have any issues with a running Emacs instance: I always have a theme loaded.

**Comment by protesilaos** [comment]
@renbus:

> In other words, how come is Spacious Padding changing the mode lines foreground and background colors? Shouldn't it simply modify the padding (thus the mode-lines borders)?

It should never touch the background or, indeed, any of the properties we did not specify. This is how `custom-set-faces` has always worked. BUT, it seems this is only true if a theme is loaded, otherwise it happily resets everything.

Do you experience this problem while not using a theme? Or does it also happen when a theme is loaded? If the latter, are you using the Emacs daemon?

**Comment by ksafford** [comment]
Interesting discovery. Yes, typically I open Emacs with the default theme and use `consult-theme` to enable a theme based on my mood --- the modus and ef-themes provide too many great options to just use the same theme all the time.

I am not using Emacs in GIU but not the daemon.

I will try to reproduce with a minimal config. May take me a day or so to find the opportunity for it.

**Comment by protesilaos** [comment]
> From: Kevin Safford ***@***.***>
> Date: Tue, 20 Aug 2024 08:11:56 -0700
>
> Interesting discovery. Yes, typically I open Emacs with the default
> theme and use `consult-theme` to enable a theme based on my mood ---
> the modus and ef-themes provide too many great options to just use the
> same theme all the time.

Try to load a them with 'load-theme' instead of Consult. Maybe this
makes a difference.

> I am not using Emacs in GIU but not the daemon.

Okay, let's keep this in mind. There may be differences in what kind of
display capabilities Emacs supports.

> I will try to reproduce with a minimal config. May take me a day or so
> to find the opportunity for it.

Thank you!

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by renbus** [comment]
Hello!

I'm happy that you're looking at this bug, because this is still an issue for me.

I do find the same strange behaviour as you do following your instructions in a "emacs -Q" instance (and I have no Emacs daemon running). Like you found out, using `(custom-set-faces)` to change the mode-line border (the box attribute) does also affect the background color if I don't have any theme loaded. In fact, if you don't have any theme loaded, `(custom-set-faces)` simply seems to reset all the face attributes, except the one you are specifically customizing :

```
;; In a "emacs -Q", with no theme loaded.

(custom-set-faces '(mode-line ((:foreground red)))
;; The mode-line foreground color is red, everything else is unspecified.

(custom-set-faces '(mode-line ((:strike-through t)))
;; The mode-line foreground color is now black (unspecified), strike-through is on.
```
If I use `(set-face-attribute)` instead of `(custom-set-faces)`, I don't have this behaviour, previous changes remain.

**Comment by protesilaos** [comment]
> From: renbus ***@***.***>
> Date: Tue, 20 Aug 2024 09:35:43 -0700
>
> Hello!
>
> I'm happy that you're looking at this bug, because this is still an issue for me.

I now realise that I missed the notification about the original post. I
am not sure how that happened. I could not find it in my email.

> [... 11 lines elided]

> If I use `(set-face-attribute)` instead of `(custom-set-faces)`, I
> don't have this behaviour, previous changes remain.

I would happily use this (and I already have macros for it), but we
cannot unset it. Or, at least, I have not found a way to do that.

Basically, we want the equivalent of this when a theme is loaded:

    (custom-set-faces
     '(mode-line nil))

The above unsets the "user" theme and keeps all of the loaded theme's
settings.

If we can find the reverse of 'set-face-attribute', then we are good to
go.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by renbus** [comment]
> I now realize that I missed the notification about the original post. I am not sure how that happened. I could not find it in my email.

Ok, no worries!

> I would happily use this (and I already have macros for it), but we cannot unset it. Or, at least, I have not found a way to do that. Basically, we want the equivalent of this when a theme is loaded: (custom-set-faces '(mode-line nil)) The above unsets the "user" theme and keeps all of the loaded theme's settings. If we can find the reverse of 'set-face-attribute', then we are good to go.

Well, I started this thread because when I would launch Emacs, I would see a grey thick border around the mode-line (which I customized the `:background` to be some kind of green). That grey border would go away (in other words, would become the same color as the background, thus visually disappear) if I would disable/re-enable Spacious padding, or reload a theme. While investigating this issue, I came up with the question at the origin of this thread.

I understand from our discussion that this is caused by unexpected behaviour form `(custom-set-faces)` while there is no theme loaded. In my own init.el, I do customize the `default-frame-alist`, then load the Modus theme, make some tweakings to it, then load the Doom modeline package, then Spacious-padding, among other things. I use the `use-package` macro to set everything up. So it kind of become hard to track what happens before what, and what affects what. So far, and because of our conversation, I now get satisfying results by making sure Spacious-padding turns on after everything using:

```
(use-package spacious-padding
   :hook (after-init . spacious-padding-mode)
   ...
```

**Comment by protesilaos** [comment]
> From: renbus ***@***.***>
> Date: Tue, 20 Aug 2024 11:52:43 -0700

> [... 9 lines elided]

> I understand from our discussion that this is caused by unexpected
> behaviour form `(custom-set-faces)` while there is no theme loaded. In
> my own init.el, I do customize the `default-frame-alist`, then load
> the Modus theme, make some tweakings to it, then load the Doom
> modeline package, then Spacious-padding, among other things. I use the
> `use-package` macro to set everything up. So it kind of become hard to
> track what happens before what, and what affects what.

My understating is that Emacs has two types of "themes". The one is the
kind of themes you load, like Modus, and the other is the "user" theme.
The latter is laid on top of the former group, merging with them and
overriding them where there is a conflict or extension.

In other words, when we use 'custom-set-faces' we do not rewrite the
faces we modify: we merely extend them with new attributes or modify
those---and only those---we specify.

The "no theme" scenario seems different though. I do not know if this is
by design or a bug in Emacs. This is worth researching further.

> So far, and because of our conversation, I now get satisfying results
> by making sure Spacious-padding turns on after everything using:
>
> ```
> (use-package spacious-padding
>    :hook (after-init . spacious-padding-mode)
>    ...
> ```

I think it makes sense for this to be loaded last, since it is meant to
operate on your existing styles. If this works for you, then we are good
for now.

I guess one option for people who do not use any theme is to do either
of the following:

1. If they like what Emacs offers out-of-the-box, they can use my
  'standard-themes'. Then modify them as they see fit.

2. If they have customisations for faces, they can collect those into a
   single theme file and then load that.

Either way, the goal is to have some theme loaded so that 'custom-set-faces'
does not misbehave.

-- 
Protesilaos Stavrou
https://protesilaos.com
