### ISSUE TITLE
Usage with doom emacs

### ISSUE THREAD

**Issue by pbaille** [protesilaos/spacious-padding#17]
Hello,

I encountered an issue using spacious-padding along doom emacs.

I was trying the following use-package declaration:

```elisp
(use-package spacious-padding
  :config
  (setq spacious-padding-widths
        '(:internal-border-width 15
          :header-line-width 4
          :mode-line-width 6
          :tab-width 4
          :right-divider-width 15
          :scroll-bar-width 8
          :fringe-width 8))
  (spacious-padding-mode)
```

But when starting doom, the paddings where not visible.
I had to `M-x spacious-padding-mode` again for them to display as expected. 

The thing that I finally understood is that there is a hook that mess with spacious-padding.

I had to add the following expression to my use-package declaration:
`(remove-hook 'doom-init-ui-hook #'window-divider-mode)`

With this it works as expected.

I am documenting this just in case someone else encounter the same behavior.

**Comment by protesilaos** [comment]
> From: Pierre Baille ***@***.***>
> Date: Fri, 21 Jun 2024 04:57:17 -0700
>
> Hello,

Hello Pierre,

> I encountered an issue using spacious-padding along doom emacs.

> [... 22 lines elided]

> I had to add the following expression to my use-package declaration:
> `(remove-hook 'doom-init-ui-hook #'window-divider-mode)`

Good to know! I will take a look at the window-divider-mode. Maybe we
can do something in spacious-padding to handle it.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by pbaille** [comment]
Perfect, thank you :)

**Comment by zibebe** [comment]
Dear Protesilaos,

I've got something similar on Vanilla Emacs 30.0.92 . When I start Emacs up, all paddings are correct. Now, if I open up a buffer in a new vertical window the space between these two is 0. The variable `spacious-padding-widths` is set to `(:internal-border-width 15 :header-line-width 4 :mode-line-width 6 :tab-width 4
                        :right-divider-width 30 :scroll-bar-width 8
                        :fringe-width 8)` which are the default settings
Now if I toggle spacious-padding off and on again the padding is correct as defined with `right-divider-width`

This is how I have configured spacious-padding.

```elisp
(use-package spacious-padding
  :ensure t
  :demand t
  :if (display-graphic-p)
  :hook (after-init . spacious-padding-mode))
```

Then this is what I tried next, but it didn't help (I thought initializing the `spacious-padding-widths` before it gets active might help

```elisp
(use-package spacious-padding
  :ensure t
  :demand t
  :if (display-graphic-p)
  :hook (after-init . spacious-padding-mode)
  :init
  (setq spacious-padding-widths
        '( :internal-border-width 15
           :header-line-width 4
           :mode-line-width 6
           :tab-width 4
           :right-divider-width 30
           :scroll-bar-width 8
           :fringe-width 8)))
```

BR, Tobias

**Comment by protesilaos** [comment]
> Update: I fixed it by removing this from my `init.el`
> 
> ```emacs-lisp
> (add-hook 'after-init-hook #'window-divider-mode)
> ```

Fine, I will check what we can do to work with `window-divider-mode`.

**Comment by protesilaos** [comment]
@zibebe Can you try again with this?

```diff
 spacious-padding.el | 2 ++
 1 file changed, 2 insertions(+)

diff --git a/spacious-padding.el b/spacious-padding.el
index b4287ca..28d2d3e 100644
--- a/spacious-padding.el
+++ b/spacious-padding.el
@@ -412,6 +412,7 @@ (defun spacious-padding--enable-mode ()
   (spacious-padding--store-default-parameters)
   (spacious-padding-modify-frame-parameters)
   (spacious-padding-set-faces)
+  (add-hook 'window-divider-mode-hook #'spacious-padding--enable-mode)
   (add-hook 'enable-theme-functions #'spacious-padding-set-faces)
   (add-hook 'after-make-frame-functions #'spacious-padding-set-parameters-of-frame))
 
@@ -419,6 +420,7 @@ (defun spacious-padding--disable-mode ()
   "Disable `spacious-padding-mode'."
   (spacious-padding-modify-frame-parameters :reset)
   (spacious-padding-unset-invisible-dividers)
+  (remove-hook 'window-divider-mode-hook #'spacious-padding--enable-mode)
   (remove-hook 'enable-theme-functions #'spacious-padding-set-faces)
   (remove-hook 'after-make-frame-functions #'spacious-padding-set-parameters-of-frame))
 
```

**Comment by zibebe** [comment]
@protesilaos this works perfect!
Thank you very much!

**Comment by protesilaos** [comment]
Just pushed the changes. Thank you!
