### ISSUE TITLE
Spacious-Padding is misaligned on opening it

### ISSUE THREAD

**Issue by breddiesucks** [protesilaos/spacious-padding#18]
I want to make clear that I am a novice and was setting up emacs from ground up with the help of forums and guides. I am using spacious padding so Emacs looks less cramped and more spacious. And I am actually very satisfied with the result, but the issue is, when I open a new instance of emacs, the padding is oriented for full screen res rather than the window size.

Emacs when booting up:
![image](https://github.com/protesilaos/spacious-padding/assets/127048853/e6f24bda-0b45-4a15-9110-eeb32d542ba7)

Emacs after resizing/using a C-x or M-x command:
![image](https://github.com/protesilaos/spacious-padding/assets/127048853/03ded294-f893-40e1-9423-dedc5a2d4401)

Could this be an issue of my window manager (herbstluftwm+xfce) or is it a issue with emacs? I can understand that this issue is very superficial and trivial, but I would love to resolve this little untied knot.

Cheers :)

**Comment by protesilaos** [comment]
> From: breddie ***@***.***>
> Date: Fri, 28 Jun 2024 22:14:37 -0700

> [... 12 lines elided]

> Could this be an issue of my window manager (herbstluftwm+xfce) or is
> it a issue with emacs? I can understand that this issue is very
> superficial and trivial, but I would love to resolve this little
> untied knot.

I think this is an issue with herbstluftwm in combination with some
default Emacs settings. Add these to your 'early-init.el':

    (setq frame-resize-pixelwise t)
    (setq frame-inhibit-implied-resize t)

Do 'M-x describe-variable' and search for those two to see how they
relate to this issue.

On the 'spacious-padding' front, we do have any code to resize windows.
This is the task of Emacs' window manager.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by breddie-normie** [comment]
The given variable change resolves the issue. Will there be any repercussions if I put these at the start of init.el instead of early-init.el. (Sorry if this sounded daft and immature, it has been a while since I troubleshooted with my dotfiles as a whole)

**Comment by protesilaos** [comment]
> From: breddie ***@***.***>
> Date: Sat, 29 Jun 2024 05:17:14 -0700
>
> The given variable change resolves the issue. Will there be any
> repercussions if I put these at the start of init.el instead of
> early-init.el. (Sorry if this sounded daft and immature, it has been a
> while since I troubleshooted with my dotfiles as a whole)

Putting them in the early-init.el makes them have effect before the
first frame is drawn. The init.el is "too late" in that regard. But they
will still work for any action/frame after the one at startup.

-- 
Protesilaos Stavrou
https://protesilaos.com
