### ISSUE TITLE
Tab compatability in PGTK build

### ISSUE THREAD

**Issue by JoaoDiogoDuarte** [protesilaos/spacious-padding#19]
Great job with this extension! The only issue is that it is not compatible with tabs, as you can see in this image:

![image](https://github.com/protesilaos/spacious-padding/assets/14338663/f6667ddc-e4ab-4a33-bf85-3d989bdfd4d1)

Is there any way around this?
Thanks!

**Comment by protesilaos** [comment]
> From: João Diogo Duarte ***@***.***>
> Date: Sun, 30 Jun 2024 14:06:47 -0700
>
> Great job with this extension! The only issue is that it is not compatible with tabs, as you can see in this image:
>
> ![image](https://github.com/protesilaos/spacious-padding/assets/14338663/f6667ddc-e4ab-4a33-bf85-3d989bdfd4d1)
>
> Is there any way around this?

There was a report about this a while ago and it turned out to be an
issue with the PGTK build of Emacs. Is this what you are using?

Because we do support tab-bar and tab-line.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by JoaoDiogoDuarte** [comment]
Ah yes, I am in fact doing that, I will also change the issue title. Do you know if the issue with PGTK got fixed?

**Comment by JoaoDiogoDuarte** [comment]
Ok, I've searched the issue list and I guess I need to wait for arch to release emacs 30 for the fix - I'll be patiently waiting!

Again, great work on this extension

**Comment by protesilaos** [comment]
> From: João Diogo Duarte ***@***.***>
> Date: Mon,  1 Jul 2024 03:45:20 -0700
>
> Ok, I've searched the issue list and I guess I need to wait for arch
> to release emacs 30 for the fix - I'll be patiently waiting!

Very well!

> Again, great work on this extension

Thank you!

-- 
Protesilaos Stavrou
https://protesilaos.com
