### ISSUE TITLE
effects mode-line box around text color

### ISSUE THREAD

**Issue by nehrbash** [protesilaos/spacious-padding#2]
I use the theme `doom-gruvbox` from `doom-themes` which provides an option to pad the mode-line `doom-gruvbox-padded-modeline`. 

>  "If non-nil, adds a 4px padding to the mode-line. Can be an integer to
determine the exact padding."

![image](https://github.com/protesilaos/spacious-padding/assets/62710600/2ee62b08-b35d-4fe8-89d6-d8766d417f49)

With spacious padding on, this border in made invisible by changing the box color to the background color. to my knowledge this would effect anyone's mode-line that has a box around text face attribute and is not a doom theme specific issue. 

![image](https://github.com/protesilaos/spacious-padding/assets/62710600/9ffc7b41-6774-45be-a461-a510955beaae)

sorry my screenshot tool can only take inactive screenshots it seems.

**Comment by protesilaos** [comment]
> From: nehrbash ***@***.***>
> Date: Fri, 15 Dec 2023 10:59:46 -0800
>
> I use the theme `doom-gruvbox` from `doom-themes` which provides an
> option to pad the mode-line `doom-gruvbox-padded-modeline`.
>
>>  "If non-nil, adds a 4px padding to the mode-line. Can be an integer to determine the exact padding."
>
> ![image](https://github.com/protesilaos/spacious-padding/assets/62710600/2ee62b08-b35d-4fe8-89d6-d8766d417f49)
>
> With spacious padding on this border in made invisible by changing the
> box color to the background color. to my knowledge this would effect
> anyone's mode-line that has a box around text face attribute and is
> not a doom theme specific issue.
>
> ![image](https://github.com/protesilaos/spacious-padding/assets/62710600/9ffc7b41-6774-45be-a461-a510955beaae)

Are the doom-themes only affecting the faces? Or are they doing
something else as well to the mode line? I do not use them and cannot
tell just by looking at the screenshots.

-- 
Protesilaos Stavrou
https://protesilaos.com
