### ISSUE TITLE
Invalid face box error

### ISSUE THREAD

**Issue by dschaehi** [protesilaos/spacious-padding#5]
Thanks for the nice package, @protesilaos!
I use it to have some margin at the top for my webcam and it works nicely.
I only get the following error message and I have no clue why I get it.
Can you help me fix it? I think the problem is a comma between each key and value, but I am not sure.
``` elisp
face-spec-set-2: Invalid face box: :line-width, 0, :color, "#002630", :style, nil
```

**Comment by protesilaos** [comment]
> Can you help me fix it? I think the problem is a comma between each key and value, but I am not sure.

Do you have the code that produces this error?

**Comment by dschaehi** [comment]
I get the error whenever I do `M-x spacious-padding-mode`.
By the way, I am a [Doom Emacs](https://github.com/doomemacs/doomemacs) user.

**Comment by protesilaos** [comment]
Strange... Can you please do `M-x toggle-debug-on-error` and then try
to reproduce the error? This will give you a backtrace. Please post it
here. Thanks!

**Comment by dschaehi** [comment]
After removing and reinstalling the `spacious-padding` package and updating of Doom Emacs the error is gone. Strange. But thanks for the help!

**Comment by protesilaos** [comment]
> From: Jae Hee Lee ***@***.***>
> Date: Sun, 25 Feb 2024 23:21:00 -0800
>
> After removing and reinstalling the spacious-padding package and
> updating of Doom Emacs the error is gone. Strange. But thanks for the
> help!

Strange... Let's assume it was some old file that stayed there and
caused a conflict.

-- 
Protesilaos Stavrou
protesilaos.com

**Comment by dschaehi** [comment]
> From: Jae Hee Lee ***@***.***> Date: Sun, 25 Feb 2024 23:21:00 -0800 After removing and reinstalling the spacious-padding package and updating of Doom Emacs the error is gone. Strange. But thanks for the help!
> Strange... Let's assume it was some old file that stayed there and caused a conflict.
> […](#)
> -- Protesilaos Stavrou protesilaos.com

Yes. We can close this issue. I'll get back to it again, should I see the error again. Thanks!
