### ISSUE TITLE
Differenciate `:internal-border-width` further

### ISSUE THREAD

**Issue by LukasCBossert** [protesilaos/spacious-padding#8]
I was wondering whether it is possible to have instead of `:internal-border-width` also e.g. `:top-border-width`. Then only a margin at the top border is applied.

In my case I am using [`sketchybar`](https://github.com/FelixKratz/SketchyBar) and in full-screenmode the Emacs window is "behind" the sketchybar. It would be totally sufficient only to have a margin on top.

Great work with this and the other packages!

**Comment by protesilaos** [comment]
> From: "Lukas C. Bossert" ***@***.***>
> Date: Thu, 14 Mar 2024 14:48:07 -0700
>
> I was wondering whether it is possible to have instead of
> `:internal-border-width` also e.g. `:top-border-width`. Then only a
> margin at the top border is applied.

I am not aware of a way to do this. Looking at the manual, we do not
have separate values for each side of the internal border.

Evaluate this to read the relevant entry:

    (info "(elisp) Layout Parameters")

If there is a way to differentiate those borders, I am happy to do it.

> In my case I am using
> [`sketchybar`](https://github.com/FelixKratz/SketchyBar) and in
> full-screenmode the Emacs window is "behind" the sketchybar. It would
> be totally sufficient only to have a margin on top.

Ah yes, that would be cool.

> Great work with this and the other packages!

Thank you!

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by protesilaos** [comment]
I don't think there is a way to do this due to Emacs' limitations. Closing now.
