### ISSUE TITLE
emacsclient -c -a ""

### ISSUE THREAD

**Issue by muello** [protesilaos/spacious-padding#9]
Hello,

thanks so much for your work on this and other very beautiful packages (like ef-themes)!

I've notice a small issue on starting up with emacsclient. Steps:

Save the following as .emacs.d/init.el:

```
(push "~/my/path/to/spacious-padding/" load-path)
(require 'spacious-padding)
(spacious-padding-mode 1)
(define-key global-map (kbd "<f8>") #'spacious-padding-mode)
```

Call ```emacsclient -c -a ""```.

Note the issues in the modeline. Others also become visible on splitting the window with ```C-x 3```.

After we press ```f8``` twice to toggle off and on again, the issues have gone away.

**Comment by muello** [comment]
NB, the issues become more visible when loading a different theme. Prepend the following to the minimal init.el above:

```
(push "~/.emacs.d/path/to/ef-themes/" load-path)
(require 'ef-themes)
;; Disable all other themes to avoid awkward blending:
(mapc #'disable-theme custom-enabled-themes)
(load-theme 'ef-night :no-confirm)
```

**Comment by bsvh** [comment]
I have an issue where the border used for the padding in the modeline is the wrong color until I reload spacious-padding-mode. I'm not sure if this is the same issue you are having, but here is a workaround I am using;

```
(defun bs-sp-workaround ()
  "Workaround issues with `spacious-padding-mode' when using emacsclient."
  (when server-mode
    (spacious-padding-mode 1)
    (remove-hook 'server-after-make-frame-hook #'bs-sp-workaround)))
(add-hook 'server-after-make-frame-hook #'bs-sp-workaround)
```

**Comment by muello** [comment]
Thanks a lot @bsvh, that's the hook I was looking for!

**Comment by protesilaos** [comment]
> From: bsvh ***@***.***>
> Date: Sat, 23 Mar 2024 14:57:06 -0700
>
> I have an issue where the border used for the padding in the modeline
> is the wrong color until I reload spacious-padding-mode. I'm not sure
> if this is the same issue you are having, but here is a workaround I
> am using;
>
> ```
> (defun bs-sp-workaround ()
>   "Workaround issues with `spacious-padding-mode' when using emacsclient."
>   (when server-mode
>     (spacious-padding-mode 1)
>     (remove-hook 'server-after-make-frame-hook #'bs-sp-workaround)))
> (add-hook 'server-after-make-frame-hook #'bs-sp-workaround)
> ```

Interesting. I am curious why we would even need this sort of
arrangement. Perhaps due to how the emacsclient frame parameters are
instantiated?

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by GaryBlackbourne** [comment]
Today I had this issue myself. I am using emacs on three machines, my home pc, my laptop, and my workstation at office. All of them run archlinux, with mostly same configurations, and the exact same emacs config. Interesting that I only experienced this issue on my workstation, but the given hook didn't solve it to me, only helped to avoid it the first time.

steps:
- emacs started as a systemd service
- run emacsclient -c (i do it from sway with a hotkey)
- issue

steps after the hook:
- emacs started as a systemd service
- run emacsclient -c
- no issue
- close and reopen emacsclient
- issue

**Comment by protesilaos** [comment]
Hello @GaryBlackbourne!

> Interesting that I only experienced this issue on my workstation

Is this using the PGTK build of Emacs (built the `--with-pgtk` flag)? That one gave me weird issues when I was trying it on GNOME+Wayland, though none were related to `spacious-padding`.

If this is not PGTK, then maybe you need the PGTK build for SwayWM. Arch has the `emacs-wayland` package for this.

As with the original report, I cannot reproduce any of this on my end. I want to understand exactly what is happening. Though I have a strong suspicion that it is not related to `spacious-padding` but to how the daemon/server sets up a new frame, perhaps in combination with the underlying graphical toolkit Emacs is built with.

**Comment by GaryBlackbourne** [comment]
Yes, I did use `--with-pgtk` with all my emacs builds. For some reason I like to build emacs from source. The thing is, I can not reproduce the issue on my laptop which also use wayland-sway and emacs with --with-pgtk. I am not very familiar with lisp, or graphical environments, but is there any way i could help you?

**Comment by protesilaos** [comment]
> For some reason I like to build emacs from source.

Please give me the value of `system-configurations-options`. This is the first step to reproducing the problem.

> but is there any way i could help you?

If we can find a minimal configuration that reliably reproduces the bug, then I can find the Elisp details.

**Comment by GaryBlackbourne** [comment]
There you go, this is my `system-configuration-options` value:

```
--without-compress-install
--with-native-compilation
--with-tree-sitter
--with-mailutils
--with-imagemagick
--with-pgtk
'CFLAGS=-O3 -fno-math-errno -funsafe-math-optimizations -fno-finite-math-only -fno-trapping-math -freciprocal-math -fno-rounding-math -fno-signaling-nans -fassociative-math -fno-signed-zeros -frename-registers -funroll-loops -mtune=native -march=native -fomit-frame-pointer -fallow-store-data-races -fno-semantic-interposition -floop-parallelize-all -ftree-parallelize-loops=4'
```

**Comment by GaryBlackbourne** [comment]
Having only the following init file (same client-server architecture) does not cause the issue:
``` lisp
(load-theme 'modus-vivendi)

(use-package spacious-padding
  :ensure t
  :config
  (spacious-padding-mode 1))
```

Also, having doom-modelien installed and configured does not have this issue:
``` lisp
(require 'package)

(load-theme 'modus-vivendi)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)

(use-package spacious-padding
  :ensure t
  :config
  (spacious-padding-mode 1))


(use-package doom-modeline
  :ensure t
  :config
  (setq doom-modeline-height 25)
  :init
  (doom-modeline-mode 1))

```

The stepps I followed to set up these configs:
- create an empty directory and create the init.el file
- run emacs server: `emacs --init-directory=. --fg-daemon=test`
- connect to the running server using: `emacsclient -c -n -s test`


Both configurations work as expected. It seems that it is not related to `spacious-padding` but to my configuration. Which is fortunate, but now, I have to debug my config.

**Comment by GaryBlackbourne** [comment]
thank you for the advice. Yesterday the problem seemed to have disappeared, but at the end of the day, occurred again.  Interesting, as if it would depend on some non deterministic thing, execution order, or smth. Unfortunately I won't have access to that machine for a week, but I will check what you recommended when i go back to the office. Thank you!

**Comment by GaryBlackbourne** [comment]
I looked into what you recommended, and found nothing suspicious.
``` lisp 
;; default-frame-alist
((fullscreen . maximized) (vertical-scroll-bars)
 (internal-border-width . 15) (right-divider-width . 30)
 (left-fringe . 8) (right-fringe . 8) (scroll-bar-width . 8))

;; after-make-frame-functions 
(spacious-padding-set-parameters-of-frame evil-init-esc
                                          pgtk-dnd-init-frame)

;; server-after-make-frame-hook
nil
``` 

This seems okay to me, except the `server-after-make-frame-hook` since that is empty. Is that possible that i am missing something there? 

My other suspect was `doom-modeline` which also edits the modeline. But after disabling that, i still have the issue with the vanilla modeline. Also tried to mess with modus themes, and comment out this two settings, since they should have an effect on the modeline, but no success.

``` lisp 

  (setq modus-themes-common-palette-overrides
        `(
          (border-mode-line-active unspecified)    ;;   <<<---------------- this
          (border-mode-line-inactive unspecified)   ;;   <<<---------- and this
 
          (bg-paren-match bg-magenta-intense)
          (underline-paren-match fg-main)

          (bg-region bg-ochre)
          (fg-region unspecified)

          ;; And expand the preset here.  Note that the ,@ works because
          ;; we use the backtick for this list, instead of a straight
          ;; quote.
          ,@modus-themes-preset-overrides-faint))
```

Is there anything that you think i am missing?

**Comment by GaryBlackbourne** [comment]
I also found, that reloading `spacious-padding` fixes the issue as previously mentioned, but reloading the theme with `modus-themes-select` also fixes the bug.

**Comment by protesilaos** [comment]
I think this all have to do with the daemon not having a frame during the time spacious-padding functions are called. There has to be some hook for us to trigger spacious-padding functions when the daemon eventually draws a frame.

Does this do anything in this regard?

```elisp
(defun test-spacious-padding-server ()
  (spacious-padding-modify-frame-parameters)
  (spacious-padding-set-faces))

(add-hook 'server-after-make-frame-hook 'test-spacious-padding-server)
```
